name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies # 종속성 설치 단계
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk python3 python3-pip virtualenv

      # libtinfo6 설치 명령어 추가
      - name: Install libtinfo6
        run: sudo apt-get install libtinfo6

      - name: Setup virtual environment
        run: |
          virtualenv venv
          source venv/bin/activate
          pip install buildozer

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
