name: Buildozer Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Android SDK 라이선스 수락 및 패키지 설치
        run: |
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;36.0.0"

      - name: Buildozer 및 의존성 설치
        run: |
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Buildozer 빌드 실행
        run: buildozer android debug

      - name: APK 파일 업로드 (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
