name: Buildozer Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Android SDK and cmdline-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          echo "Android SDK installed at $ANDROID_HOME"
          # 디렉토리 확인
          ls -l $ANDROID_HOME/cmdline-tools/latest/bin
        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Accept Android SDK licenses
        run: |
          # sdkmanager 경로 확인 후 실행
          ls -l $ANDROID_HOME/cmdline-tools/latest/bin
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Install Android SDK packages
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;36.0.0"
        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Buildozer 및 의존성 설치
        run: |
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Buildozer 빌드 실행
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          buildozer android debug

      - name: APK 파일 업로드 (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
