name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update package repositories
        run: sudo apt-get update

      - name: Add deadsnakes PPA
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update

      - name: Install dependencies
        run: |
          sudo apt-get install -y git zip unzip openjdk-11-jdk python3.11 python3.11-distutils virtualenv libtinfo6

      - name: Install pip for python3.11
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3.11 get-pip.py

      - name: Setup virtual environment
        run: |
          virtualenv -p python3.11 venv
          source venv/bin/activate
          pip install buildozer setuptools

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
