name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk python3.11 python3.11-pip virtualenv

      - name: Setup virtual environment
        run: |
          virtualenv -p python3.11 venv
          source venv/bin/activate
          pip install buildozer setuptools

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: bin/*.apk
