name: Buildozer Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Android SDK 및 cmdline-tools 설치
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: 환경 변수 설정
        run: |
          echo "export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc
        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Android SDK 라이선스 수락
        run: yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Android SDK 패키지 설치
        run: |
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;36.0.0"

      - name: Buildozer 및 의존성 설치
        run: |
          sudo apt update -y
          sudo apt install -y git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Buildozer 빌드 실행
        run: buildozer android debug

      - name: APK 파일 업로드 (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
